### ISSUE TITLE
Unexpected behavior passing classes to component svg

### ISSUE THREAD

**Issue by cameronmbell** [poppa/sveltekit-svg#12]
The expected behavior is that these two behave the same, but the latter does not work.

```svelte
<!-- Inline the svg -->
<svg class="my-class" viewbox="0 0 128 128">
    <!-- ... -->
</svg>

<style>
    .my-class {
        width: 16px;
        height: 16px;
    }
</style>
```
However this does not work:
```svelte
<!-- Import as component -->
<script>
    import Svg from 'test.svg';
</script>

<Svg class="my-class" />

<style>
    .my-class {
        width: 16px;
        height: 16px;
    }
</style>
```

With a real svg when I inspect the generated elements in chrome, the inlined svg generates: 
```
<svg class="my-class s-Uap-jPRb-uiE" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 128 128" style="isolation: isolate;">
```
While the component svg generates:
```
<svg class="my-class" xmlns="http://www.w3.org/2000/svg" style="isolation:isolate" viewBox="0 0 128 128">
```
Notice the missing svelte class.

**Comment by poppa** [comment]
Hm, I do think this is the expected behavior. 

I'm pretty sure this is how Svelte works. `class` on a component is just an arbitrary attribute and there is no way Svelte knows it's a CSS class name that should be propagated down the component tree. `class` only means what you'd expect on DOM elements. _(I'm pretty sure this is how it works, but I'm more than happy to be convinced otherwise)_

If you wan't `my-class` to apply to the included component you have to add `:global()` to your class name:

```svelte
<style>
:global(.my-class) {
  width: 16px;
  height: 16px;
}
</style>
```

**Comment by cameronmbell** [comment]
Ok thanks for the quick reply that makes sense. I would argue that although that is the default behavior for svelte components, an svg component should act just as an inline svg. It is your library and ultimately your decision and so I am closing this issue.

**Comment by DanielRios549** [comment]
It would be great if the output SVG had the scoped class from Svelte, first of all, using `:global` is dull, second, in cases where the icon is the root of a component, the styles will change all SVGs in the document since there is no scoped class in a parent element.

The solution for this problem is to use `<svelte:component class="something" this={Icon}/>`, this is not ideal, you still need to use `:global`, but at least there will be no other icons with `something` class in the document, so the stiles for `:global(svg.something)` will not change anything outside the component.
