### ISSUE TITLE
BUG: SVG component not resizing

### ISSUE THREAD

**Issue by moonlitgrace** [poppa/sveltekit-svg#62]
version:
```bash
"@poppanator/sveltekit-svg": "^5.0.0-svelte5.5",
```

When i use it like:
```svelte
<script lang="ts">
    import CoreIcons from '$lib/assets/core-icons.svg?component'
</script>

<CoreIcons class="w-20" />
```

output:
![Screenshot 2024-08-31 at 14-09-05 ](https://github.com/user-attachments/assets/9dbd18f0-7649-4ba8-b2bb-ae9cc6e93d8c)

when i remove `class`:
![Screenshot 2024-08-31 at 14-09-23 ](https://github.com/user-attachments/assets/33f3cf33-5442-491a-8943-53c8126b5363)

it seems cropped instead resize.
i mean - the first one seems cropped and 2nd one is the full svg

**Comment by poppa** [comment]
I need a better bug report than this! I can't do anything from this information, sorry.

**Comment by poppa** [comment]
Feel free to re-open the issue with more information.

**Comment by progzone122** [comment]
I had a similar problem, it is fixed by removing width and height from svg

`
<GitHubLogo class="w-10" />
`

![Image](https://github.com/user-attachments/assets/a5cfeef6-980f-496c-88a4-6ec8754bdf6a)
![Image](https://github.com/user-attachments/assets/396dfc5e-b5e8-4866-9020-26de9c2fcaa6)

![Image](https://github.com/user-attachments/assets/16c7a963-6a2d-40b9-bbf9-aa4ca1fb5c84)
![Image](https://github.com/user-attachments/assets/30a2bd95-307d-4ebd-b81a-850bfa93b05a)
